// mjsui-quickstart-react-ts/src/Viewer.tsx
import { AnnotationState } from "@markerjs/markerjs3";
import { AnnotationViewer } from "@markerjs/markerjs-ui";
import { useEffect, useRef } from "react";

type Props = {
  targetImage: string;
  annotation: AnnotationState | null;
};

const Viewer = ({ targetImage, annotation }: Props) => {
  const viewerContainer = useRef<HTMLDivElement | null>(null);
  const viewer = useRef<AnnotationViewer | null>(null);

  useEffect(() => {
    if (!viewer.current && viewerContainer.current) {
      const targetImg = document.createElement("img");
      targetImg.src = targetImage;

      viewer.current = new AnnotationViewer();
      viewer.current.targetImage = targetImg;

      viewerContainer.current.appendChild(viewer.current);
    }
  }, [targetImage]);

  useEffect(() => {
    if (annotation) {
      viewer.current?.show(annotation);
    }
  }, [annotation]);

  return <div ref={viewerContainer}></div>;
};

export default Viewer;

// mjsui-quickstart-vue-ts/src/components/Viewer.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { type AnnotationState } from '@markerjs/markerjs3'
import { AnnotationViewer } from '@markerjs/markerjs-ui'

const props = defineProps<{
  targetImage: string
  annotation: AnnotationState
}>()

const viewerContainer = ref<HTMLDivElement | null>(null)
const viewer = ref<AnnotationViewer | null>(null)

// Initialize AnnotationViewer on mount
onMounted(() => {
  if (viewerContainer.value) {
    const targetImg = document.createElement('img')
    targetImg.src = props.targetImage

    viewer.value = new AnnotationViewer()
    viewer.value.targetImage = targetImg

    viewerContainer.value.appendChild(viewer.value)

    if (props.annotation) {
      viewer.value.show(props.annotation)
    }
  }
})

// Update view when annotation changes
watch(() => props.annotation, (newAnnotation) => {
  viewer.value?.show(newAnnotation)
})
</script>

<template>
  <div ref="viewerContainer"></div>
</template>
