// mjsui-quickstart-react-ts/src/App.tsx
import { useState } from "react";
import "./App.css";
import sampleImage from "/sample-image.png";
import { AnnotationState } from "@markerjs/markerjs3";
import Editor from "./Editor";
import Viewer from "./Viewer";

function App() {
  const [annotation, setAnnotation] = useState<AnnotationState | null>(null);
  const handleSave = (annotation: AnnotationState, dataUrl?: string) => {
    setAnnotation(annotation);
    if (dataUrl) {
      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = "annotation.png";
      link.click();
    }
  };

  return (
    <>
      <Editor targetImage={sampleImage} onSave={handleSave} />
      <Viewer targetImage={sampleImage} annotation={annotation} />
    </>
  );
}

export default App;

// mjsui-quickstart-vue-ts/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { AnnotationState } from '@markerjs/markerjs3'
import Editor from './components/Editor.vue'
import Viewer from './components/Viewer.vue'

// Path to our sample image
const sampleImage = '/sample-image.png'

// State to store the current annotation
const annotation = ref<AnnotationState | null>(null)

// Handler for when editor saves an annotation
const handleSave = (newAnnotation: AnnotationState, dataUrl?: string) => {
  annotation.value = newAnnotation
  if (dataUrl) {
    const link = document.createElement("a");
    link.href = dataUrl;
    link.download = "annotation.png";
    link.click();
  }  
}
</script>

<template>
  <Editor :targetImage="sampleImage" @save="handleSave" />
  <Viewer :targetImage="sampleImage" :annotation="annotation" />
</template>
